[algokit]
min_version = "v2.0.0"

[project]
type = "frontend"
name = 'ui'
artifacts = "src/contracts"

[project.run]
build = { commands = ['npm run build'], description = 'Build frontend' }
init = { commands = ['algokit localnet reset && npm run init'], description = 'bootstrap the contracts' }